.TH tse\-manager 8 "May 2007" tse-utils "Tse"
.SH NAME
tse-manager \- Tse key manager.

.SH DESCRIPTION
\fBtse-manager\fP is an application that manages Tse objects such as keys.

You can use \fBtse-manager\fP to ask key modules to generate new keys for you, for instance.

.SH "SEE ALSO"
.PD 0
.TP
\fBtse\fP(7), \fBtsed\fP(8), \fBmount.tse\fP(8)

.TP
\fI/usr/share/doc/tse-utils/tse-faq.html\fP

.TP
\fIhttp://tse.org/\fP
.PD

.SH AUTHOR
This manpage was written by William Lima <wlima.amadeus@gmail.com> for the Ubuntu system (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
