.TH tse-unwrap-passphrase 1 2008-07-21 tse-utils "Tse"
.SH NAME
tse-unwrap-passphrase \- unwrap an Tse mount passphrase from file.

.SH SYNOPSIS
\fBtse-unwrap-passphrase [file]\fP

printf "%s" "wrapping passphrase" | \fBtse-unwrap-passphrase [file] -\fP

.SH DESCRIPTION
\fBtse-unwrap-passphrase\fP is a utility to unwrap an Tse mount passphrase from file, using a specified wrapping passphrase, and display the decrypted result on standard out.

.SH SEE ALSO
.PD 0
.TP
\fBtse\fP(7), \fBtse-rewrap-passphrase\fP(1), \fBtse-wrap-passphrase\fP(1)

.TP
\fI/usr/share/doc/tse-utils/tse-faq.html\fP

.TP
\fIhttp://tse.org/\fP
.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
