.TH tsed 8 "May 2007" tse-utils "Tse"
.SH NAME
tsed \- user\-space Tse daemon.

.SH DESCRIPTION
\fBtsed\fP is a userspace daemon that runs as the user performing file operations under the Tse mount point. It services public key requests from the Tse kernel module; these requests are sent via /dev/tse on file open events. tsed only needs to be run when a mount is done with a public key module.

The daemon can be started simply by running \fItsed\fP. tsed will register itself with the kernel as the daemon that should service all Tse filesystem requests done under the context of the user who runs the daemon.

.SH "SEE ALSO"
.PD 0
.TP
\fBtse\fP(7), \fBtse-manager\fP(8), \fBmount.tse\fP(8)

.TP
\fI/usr/share/doc/tse-utils/tse-faq.html\fP

.TP
\fIhttp://tse.org/\fP
.PD

.SH AUTHOR
This manpage was written by William Lima <wlima.amadeus@gmail.com> for the Ubuntu system (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
